version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: EmprestimoLivros
    environment:
      ACCEPT_EULA: Y
      MSSQL_USER: sa
      MSSQL_SA_PASSWORD: 1q2w3e4r@#$
      MSSQL_DATABASE: livrosdb
    ports:
      - "1433:1433"
    volumes:
      - ~/docker:/var/opt/mssql/data
    
  emprestimolivros:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - EmprestimoLivros
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
